-- ============================================
-- JordanMarket Complete Database Migration
-- Run this file in Supabase SQL Editor to set up the entire database
-- ============================================

-- IMPORTANT: Run migrations in order:
-- 1. 001_core_schema.sql
-- 2. 002_products_schema.sql
-- 3. 003_shopping_schema.sql
-- 4. 004_ratings_schema.sql
-- 5. 005_wallet_schema.sql
-- 6. 006_notifications_schema.sql
-- 7. 007_support_schema.sql
-- 8. 008_audit_log_schema.sql
-- 9. 009_rls_policies_part1.sql
-- 10. 010_rls_policies_part2.sql
-- 11. 011_storage_buckets.sql (Bucket creation in Dashboard)
-- 12. 012_seed_data.sql

-- ============================================
-- STORAGE BUCKET SETUP (Manual in Dashboard)
-- ============================================
-- 
-- Go to Supabase Dashboard > Storage and create these buckets:
--
-- 1. product-images (Public)
--    - Anyone can read
--    - Authenticated approved sellers can upload
--
-- 2. kyc-documents (Private)
--    - Owner can read/write
--    - Admins can read
--
-- 3. avatars (Public)  
--    - Anyone can read
--    - Owner can manage
--
-- ============================================
-- ADMIN USER SETUP
-- ============================================
--
-- After registering your first user, promote them to admin:
-- SELECT promote_to_admin('your-email@example.com');
--
-- ============================================
